# Generated by Django 4.0.4 on 2022-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dataCreation',
            new_name='dateCreation',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
